version: 2.1

go_15: &go_15
  docker:
    - image: cimg/go:1.15

go_16: &go_16
  docker:
    - image: cimg/go:1.16

linting: &linting
  steps:
    - checkout
    - restore_cache:
        name: Restore go modules cache
        keys:
          - mod-{{ checksum "go.sum" }}
    - run: make install-lint
    - run: make lint
    - save_cache:
        name: Save go modules cache
        key: mod-{{ checksum "go.sum" }}
        paths:
          - "/go/pkg/mod"

build_and_test: &build_and_test
  steps:
    - checkout
    - restore_cache:
        name: Restore go modules cache
        keys:
          - mod-{{ checksum "go.sum" }}
    - run: make build
    - run: make test
    - save_cache:
        name: Save go modules cache
        key: mod-{{ checksum "go.sum" }}
        paths:
          - "/go/pkg/mod"

jobs:
  go_15_build_and_test:
    <<: [*go_15, *build_and_test]
  go_15_linting:
    <<: [*go_15, *linting]
  go_16_build_and_test:
    <<: [*go_16, *build_and_test]
  go_16_linting:
    <<: [*go_16, *linting]

workflows:
  golang-workflow:
    jobs:
      - go_15_linting
      - go_15_build_and_test:
          requires:
            - go_15_linting
      - go_16_linting
      - go_16_build_and_test:
          requires:
            - go_16_linting
