version: 2.1

go_15: &go_15
  docker:
    - image: cimg/go:1.15

go_16: &go_16
  docker:
    - image: cimg/go:1.16

linting: &linting
  steps:
    - checkout
    - run:
        name: lint
        command: |
          circleci tests split go_services.txt | xargs -L 1 bash -c 'cd "$0" && golangci-lint --timeout 3m run -v ./...'
    # - run: make install-lint
    # - run: make lint

build_and_test: &build_and_test
  steps:
    - checkout
    - run: make build
    - run: make test

jobs:
  go_15_build_and_test:
    <<: [*go_15, *build_and_test]
  go_15_linting:
    <<: [*go_15, *linting]
  go_16_build_and_test:
    <<: [*go_16, *build_and_test]
  go_16_linting:
    <<: [*go_16, *linting]

workflows:
  golang-workflow:
    jobs:
      - go_15_linting
      - go_15_build_and_test:
          requires:
            - go_15_linting
      - go_16_linting
      - go_16_build_and_test:
          requires:
            - go_16_linting
