version: 2.1

go_15: &go_15
  docker:
    - image: cimg/go:1.15

go_16: &go_16
  docker:
    - image: cimg/go:1.16

service_a: &service_a
  working_directory: /go/src/github.com/smith-30/monorepo/service_a

service_b: &service_b
  working_directory: /go/src/github.com/smith-30/monorepo/service_b

go_build_and_test_steps: &go_build_and_test_steps
  - checkout
  - run: make build
  - run: make test

build_and_test: &build_and_test
  steps:
    - checkout
    - restore_cache:
        name: Restore go modules cache
        keys:
          - mod-{{ checksum "go.sum" }}
    - run: make install-lint
    - run: make lint
    - run: make build
    - run: make test
    - save_cache:
        name: Save go modules cache
        key: mod-{{ checksum "go.sum" }}
        paths:
          - "/go/pkg/mod"

jobs:
  go_15_build_and_test:
    <<: [*go_15, *service_a, *build_and_test]
  go_16_build_and_test:
    <<: [*go_16, *service_a, *build_and_test]

workflows:
  golang-workflow:
    jobs:
      - go_15_build_and_test
      - go_16_build_and_test
