version: 2.1

go_15: &go_15
  docker:
    - image: circleci/golang:1.15

go_16: &go_16
  docker:
    - image: circleci/golang:1.16

go_mod_download: &go_mod_download
  steps:
    - checkout
    - restore_cache:
        name: Restore go modules cache
        keys:
          - mod-{{ checksum "go.sum" }}
    - run: make build
    - save_cache:
        name: Save go modules cache
        key: mod-{{ checksum "go.sum" }}
        paths:
          - "/go/pkg/mod"

linting: &linting
  steps:
    - checkout
    - restore_cache:
        name: Restore go modules cache
        keys:
          - mod-{{ checksum "go.sum" }}
    - run: make fmt-diff
    - run: make vet
    - run: make install-lint
    - run: make lint
    - save_cache:
        name: Save go modules cache
        key: mod-{{ checksum "go.sum" }}
        paths:
          - "/go/pkg/mod"

jobs:
  go_15_go_mod_download:
    <<: [*go_15, *go_mod_download]
  go_15_linting:
    <<: [*go_15, *linting]
  go_16_go_mod_download:
    <<: [*go_16, *go_mod_download]
  go_16_linting:
    <<: [*go_16, *linting]

workflows:
  golang-workflow:
    jobs:
      - go_15_go_mod_download
      - go_15_linting:
          requires:
            - go_15_go_mod_download
      - go_16_go_mod_download
